import '@js/counter.config'
import '@js/gallery.config'
import '@js/parallax.config'
import '@js/modal.config'
import '@js/select.config'
import '@js/slide.config'
import '@js/smoothscroll.config'
import '@js/tab.config'
import '@js/main.config'

import '@css/global.css'